import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProviderComponent } from "./providers/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning={true}>
      <link rel="shortcut icon" href="/Logo.png" />
      <title>Triviajs</title>
      <SessionProviderComponent>
        <body className={inter.className}>{children}</body>
      </SessionProviderComponent>
    </html>
  );
}
